### ISSUE TITLE
Can't get email address.

### ISSUE THREAD

**Issue by fagianijunior** [thogg4/omniauth-strava#6]
auth.info.email is not available any more?

My scope is "view_private"

I see on return a field named username and it is filled now, but email is nil.

**Comment by krachtstefan** [comment]
Just stumpled upon this issue. Emails are not available anymore since january 2019

> Email address is no longer part of the profile:read_all scope and is removed from the athlete model.

source: https://developers.strava.com/docs/oauth-updates/

**Comment by thogg4** [comment]
Thanks for the info @krachtstefan
