### ISSUE TITLE
How do I call native app for authentication?

### ISSUE THREAD

**Issue by ajayrds** [thogg4/omniauth-strava#8]
Hi,
I'm a novice in RoR and found this great gem+strategy super useful for a mobile app i'm building with react native as front end.

Strava now has authentication via native mobile apps and I was wondering how/if I can use this strategy to use that instead of web based auth. (many users forget their strava password and app based auth would remove a big point of friction)

Thank you!

Regards,
Ajay

**Comment by thogg4** [comment]
This should give you everything you need to get an oauth token, I am not familiar with react native and what you would need to connect those pieces, but I think its possible.
